package integrations

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"dailytrack/db"
	"dailytrack/models"
)

var ErrObsidianVaultPathRequired = errors.New("obsidian vault path required")

func ExportObsidianEntry(cfg *models.Config, entry *models.Entry) error {
	if cfg == nil || entry == nil || !cfg.App.Obsidian.Enabled {
		return nil
	}

	vaultPath := strings.TrimSpace(cfg.App.Obsidian.VaultPath)
	if vaultPath == "" {
		return ErrObsidianVaultPathRequired
	}

	dir := vaultPath
	if folder := strings.TrimSpace(cfg.App.Obsidian.DailyFolder); folder != "" {
		dir = filepath.Join(vaultPath, folder)
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	path := filepath.Join(dir, entry.Date+".md")
	return os.WriteFile(path, []byte(renderObsidianEntry(cfg, entry)), 0644)
}

func renderObsidianEntry(cfg *models.Config, entry *models.Entry) string {
	var sections []string
	for _, cat := range cfg.Categories {
		var lines []string
		for _, tracker := range cat.Trackers {
			value, ok := entry.Data[tracker.ID]
			if !ok {
				continue
			}
			if line, ok := formatObsidianTrackerLine(tracker, value); ok {
				lines = append(lines, line)
			}
		}
		if len(lines) == 0 {
			continue
		}
		sections = append(sections, "## "+cat.Name+"\n"+strings.Join(lines, "\n"))
	}

	parts := []string{
		"# " + entry.Date,
		"Generated by GoTrack",
	}
	if len(sections) > 0 {
		parts = append(parts, strings.Join(sections, "\n\n"))
	}
	return strings.Join(parts, "\n\n") + "\n"
}

func formatObsidianTrackerLine(tracker models.Tracker, value interface{}) (string, bool) {
	switch tracker.Type {
	case models.TrackerBinary:
		if b, ok := value.(bool); ok {
			if b {
				return fmt.Sprintf("- %s: Yes", tracker.Name), true
			}
			return fmt.Sprintf("- %s: No", tracker.Name), true
		}
	case models.TrackerDuration, models.TrackerCount, models.TrackerNumeric:
		if n, ok := numericValue(value); ok {
			unit := tracker.Unit
			if strings.TrimSpace(unit) == "" {
				unit = models.DefaultUnit(tracker.Name, tracker.Type)
			}
			if unit == "" {
				return fmt.Sprintf("- %s: %s", tracker.Name, formatFloat(n)), true
			}
			return fmt.Sprintf("- %s: %s %s", tracker.Name, formatFloat(n), unit), true
		}
	case models.TrackerRating:
		if n, ok := numericValue(value); ok {
			return fmt.Sprintf("- %s: %s/5", tracker.Name, formatFloat(n)), true
		}
	case models.TrackerText:
		if s, ok := value.(string); ok && strings.TrimSpace(s) != "" {
			return fmt.Sprintf("- %s: %s", tracker.Name, s), true
		}
	}
	return "", false
}

// WriteWeeklyReport generates a Markdown weekly report and writes it to the
// Obsidian vault. The file is named week_YYYY-WW.md and placed in the same
// folder as daily entries. Returns the file path written.
func WriteWeeklyReport(cfg *models.Config, entries []models.Entry, anchor time.Time) (string, error) {
	if cfg == nil || !cfg.App.Obsidian.Enabled {
		return "", errors.New("obsidian not enabled")
	}
	vaultPath := strings.TrimSpace(cfg.App.Obsidian.VaultPath)
	if vaultPath == "" {
		return "", ErrObsidianVaultPathRequired
	}
	dir := vaultPath
	if folder := strings.TrimSpace(cfg.App.Obsidian.DailyFolder); folder != "" {
		dir = filepath.Join(vaultPath, folder)
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", err
	}

	year, week := anchor.ISOWeek()
	filename := fmt.Sprintf("week_%04d-%02d.md", year, week)
	path := filepath.Join(dir, filename)

	content := renderWeeklyReport(cfg, entries, anchor)
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return "", err
	}
	return path, nil
}

func renderWeeklyReport(cfg *models.Config, entries []models.Entry, anchor time.Time) string {
	start, end := db.WeekBounds(anchor)
	year, week := anchor.ISOWeek()
	sStr := start.Format("2006-01-02")
	eStr := end.Format("2006-01-02")

	var b strings.Builder
	b.WriteString(fmt.Sprintf("# Week %d — %d\n\n", week, year))
	b.WriteString(fmt.Sprintf("> %s → %s\n\n", start.Format("Jan 2"), end.Format("Jan 2")))

	// Entry count / logging rate.
	logged := 0
	totalDays := int(end.Sub(start).Hours()/24) + 1
	for _, e := range entries {
		if e.Date >= sStr && e.Date <= eStr {
			logged++
		}
	}
	b.WriteString(fmt.Sprintf("**Logged:** %d / %d days\n\n", logged, totalDays))

	// Binary trackers.
	var binLines []string
	for _, c := range cfg.Categories {
		for _, t := range c.Trackers {
			if t.Type != models.TrackerBinary {
				continue
			}
			h, tot := db.BinaryHitsInRange(entries, t.ID, start, end)
			if tot == 0 {
				continue
			}
			pct := float64(h) / float64(tot) * 100
			prev := anchor.AddDate(0, 0, -7)
			ps, pe := db.WeekBounds(prev)
			ph, ptot := db.BinaryHitsInRange(entries, t.ID, ps, pe)
			ppct := 0.0
			if ptot > 0 {
				ppct = float64(ph) / float64(ptot) * 100
			}
			arrow := "→"
			if pct > ppct+0.5 {
				arrow = "▲"
			} else if pct < ppct-0.5 {
				arrow = "▼"
			}
			binLines = append(binLines, fmt.Sprintf("- **%s**: %d/%d (%.0f%%) %s", t.Name, h, tot, pct, arrow))
		}
	}
	if len(binLines) > 0 {
		b.WriteString("## Binary Habits\n\n")
		b.WriteString(strings.Join(binLines, "\n"))
		b.WriteString("\n\n")
	}

	// Numeric / duration / count trackers.
	var numLines []string
	for _, c := range cfg.Categories {
		for _, t := range c.Trackers {
			if t.Type != models.TrackerDuration && t.Type != models.TrackerCount && t.Type != models.TrackerNumeric {
				continue
			}
			var val float64
			if t.Type == models.TrackerNumeric {
				avg, cnt := db.AvgInRange(entries, t.ID, start, end)
				if cnt == 0 {
					continue
				}
				val = avg
			} else {
				val = db.SumInRange(entries, t.ID, start, end)
				if val == 0 {
					continue
				}
			}
			unit := t.Unit
			suffix := ""
			if strings.TrimSpace(unit) != "" {
				suffix = " " + unit
			}
			line := fmt.Sprintf("- **%s**: %s%s", t.Name, formatFloat(val), suffix)
			if t.WeeklyTarget != nil && *t.WeeklyTarget > 0 {
				pct := val / *t.WeeklyTarget * 100
				line += fmt.Sprintf(" (%.0f%% of %.0f target)", pct, *t.WeeklyTarget)
			}
			numLines = append(numLines, line)
		}
	}
	if len(numLines) > 0 {
		b.WriteString("## Numeric Trackers\n\n")
		b.WriteString(strings.Join(numLines, "\n"))
		b.WriteString("\n\n")
	}

	b.WriteString("---\n*Generated by GoTrack*\n")
	return b.String()
}

func numericValue(v interface{}) (float64, bool) {
	switch n := v.(type) {
	case float64:
		return n, true
	case int:
		return float64(n), true
	default:
		return 0, false
	}
}

func formatFloat(v float64) string {
	return strconv.FormatFloat(v, 'f', -1, 64)
}
