package integrations

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"dailytrack/models"
)

func sampleConfig() *models.Config {
	work := models.NewTracker("Deep Work", models.TrackerDuration)
	win := models.NewTracker("Main Win", models.TrackerText)
	didCode := models.NewTracker("Coding", models.TrackerBinary)

	cat := models.NewCategory("Productivity", "#00ADD8")
	cat.Trackers = []models.Tracker{work, didCode, win}

	return &models.Config{
		SetupComplete: true,
		App: models.AppSettings{
			Theme: models.ThemeGoTrack,
		},
		Categories: []models.Category{cat},
	}
}

func sampleEntry(date string, cfg *models.Config) *models.Entry {
	trackers := cfg.Categories[0].Trackers
	return &models.Entry{
		Date: date,
		Data: map[string]interface{}{
			trackers[0].ID: float64(45),
			trackers[1].ID: true,
			trackers[2].ID: "Shipped exporter",
		},
	}
}

func TestExportObsidianEntry_DisabledDoesNothing(t *testing.T) {
	vault := t.TempDir()
	cfg := sampleConfig()
	cfg.App.Obsidian.VaultPath = vault
	entry := sampleEntry("2026-04-17", cfg)

	if err := ExportObsidianEntry(cfg, entry); err != nil {
		t.Fatalf("ExportObsidianEntry() error = %v, want nil", err)
	}

	path := filepath.Join(vault, "2026-04-17.md")
	if _, err := os.Stat(path); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("os.Stat(%q) error = %v, want not-exist", path, err)
	}
}

func TestExportObsidianEntry_WritesMarkdownNote(t *testing.T) {
	vault := t.TempDir()
	cfg := sampleConfig()
	cfg.App.Obsidian.Enabled = true
	cfg.App.Obsidian.VaultPath = vault
	cfg.App.Obsidian.DailyFolder = "daily/gotrack"
	entry := sampleEntry("2026-04-17", cfg)

	if err := ExportObsidianEntry(cfg, entry); err != nil {
		t.Fatalf("ExportObsidianEntry() error = %v, want nil", err)
	}

	path := filepath.Join(vault, "daily/gotrack", "2026-04-17.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%q) error = %v", path, err)
	}
	content := string(data)

	wantParts := []string{
		"# 2026-04-17",
		"Generated by GoTrack",
		"## Productivity",
		"- Deep Work: 45 minutes",
		"- Coding: Yes",
		"- Main Win: Shipped exporter",
	}
	for _, part := range wantParts {
		if !strings.Contains(content, part) {
			t.Fatalf("content missing %q\n%s", part, content)
		}
	}
}

func TestExportObsidianEntry_RewritesSameDateFile(t *testing.T) {
	vault := t.TempDir()
	cfg := sampleConfig()
	cfg.App.Obsidian.Enabled = true
	cfg.App.Obsidian.VaultPath = vault
	entry := sampleEntry("2026-04-17", cfg)

	if err := ExportObsidianEntry(cfg, entry); err != nil {
		t.Fatalf("first ExportObsidianEntry() error = %v", err)
	}

	entry.Data[cfg.Categories[0].Trackers[2].ID] = "Updated summary"
	if err := ExportObsidianEntry(cfg, entry); err != nil {
		t.Fatalf("second ExportObsidianEntry() error = %v", err)
	}

	path := filepath.Join(vault, "2026-04-17.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%q) error = %v", path, err)
	}
	content := string(data)
	if strings.Contains(content, "Shipped exporter") {
		t.Fatalf("content still has stale summary\n%s", content)
	}
	if !strings.Contains(content, "Updated summary") {
		t.Fatalf("content missing updated summary\n%s", content)
	}
}

func TestExportObsidianEntry_MissingVaultPath(t *testing.T) {
	cfg := sampleConfig()
	cfg.App.Obsidian.Enabled = true
	entry := sampleEntry("2026-04-17", cfg)

	err := ExportObsidianEntry(cfg, entry)
	if !errors.Is(err, ErrObsidianVaultPathRequired) {
		t.Fatalf("ExportObsidianEntry() error = %v, want %v", err, ErrObsidianVaultPathRequired)
	}
}
