package integrations

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"dailytrack/models"
)

var ErrObsidianVaultPathRequired = errors.New("obsidian vault path required")

func ExportObsidianEntry(cfg *models.Config, entry *models.Entry) error {
	if cfg == nil || entry == nil || !cfg.App.Obsidian.Enabled {
		return nil
	}

	vaultPath := strings.TrimSpace(cfg.App.Obsidian.VaultPath)
	if vaultPath == "" {
		return ErrObsidianVaultPathRequired
	}

	dir := vaultPath
	if folder := strings.TrimSpace(cfg.App.Obsidian.DailyFolder); folder != "" {
		dir = filepath.Join(vaultPath, folder)
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	path := filepath.Join(dir, entry.Date+".md")
	return os.WriteFile(path, []byte(renderObsidianEntry(cfg, entry)), 0644)
}

func renderObsidianEntry(cfg *models.Config, entry *models.Entry) string {
	var sections []string
	for _, cat := range cfg.Categories {
		var lines []string
		for _, tracker := range cat.Trackers {
			value, ok := entry.Data[tracker.ID]
			if !ok {
				continue
			}
			if line, ok := formatObsidianTrackerLine(tracker, value); ok {
				lines = append(lines, line)
			}
		}
		if len(lines) == 0 {
			continue
		}
		sections = append(sections, "## "+cat.Name+"\n"+strings.Join(lines, "\n"))
	}

	parts := []string{
		"# " + entry.Date,
		"Generated by GoTrack",
	}
	if len(sections) > 0 {
		parts = append(parts, strings.Join(sections, "\n\n"))
	}
	return strings.Join(parts, "\n\n") + "\n"
}

func formatObsidianTrackerLine(tracker models.Tracker, value interface{}) (string, bool) {
	switch tracker.Type {
	case models.TrackerBinary:
		if b, ok := value.(bool); ok {
			if b {
				return fmt.Sprintf("- %s: Yes", tracker.Name), true
			}
			return fmt.Sprintf("- %s: No", tracker.Name), true
		}
	case models.TrackerDuration, models.TrackerCount, models.TrackerNumeric:
		if n, ok := numericValue(value); ok {
			unit := tracker.Unit
			if strings.TrimSpace(unit) == "" {
				unit = models.DefaultUnit(tracker.Name, tracker.Type)
			}
			if unit == "" {
				return fmt.Sprintf("- %s: %s", tracker.Name, formatFloat(n)), true
			}
			return fmt.Sprintf("- %s: %s %s", tracker.Name, formatFloat(n), unit), true
		}
	case models.TrackerRating:
		if n, ok := numericValue(value); ok {
			return fmt.Sprintf("- %s: %s/5", tracker.Name, formatFloat(n)), true
		}
	case models.TrackerText:
		if s, ok := value.(string); ok && strings.TrimSpace(s) != "" {
			return fmt.Sprintf("- %s: %s", tracker.Name, s), true
		}
	}
	return "", false
}

func numericValue(v interface{}) (float64, bool) {
	switch n := v.(type) {
	case float64:
		return n, true
	case int:
		return float64(n), true
	default:
		return 0, false
	}
}

func formatFloat(v float64) string {
	return strconv.FormatFloat(v, 'f', -1, 64)
}
